media: files

content:
  - name: AboutAuthor
    type: file
    path: _data/AboutAuthor.json
    fields:
      - name: Name
        type: string

      - name: Expertise
        type: string

      - name: Pic
        type: image
        
      - name: Desciption
        type: rich-text
        options:
          switcher: false

  - name: Books
    path: _data/BooksData
    type: collection
    format: json
    filename: "{slug}.json"
    view:
      fields: [Name, Pic, Topic, PublishedDate, Link]
      primary: Name
      sort: [PublishedDate, Name, Topic]
      default:
        sort: PublishedDate
        order: desc

    fields:
      - name: Name
        type: string
        required: true
      
      - name: PublishedDate
        type: date
        required: true
        
      - name: Pic
        type: image

      - name: Topic
        type: string

      - name: About
        type: rich-text
        options:
          switcher: false

      - name: Link
        type: string

  - name: ArticleCategories
    label: Categories
    type: collection
    path: _data/categories
    format: json
    filename: "{primary}.json"
    fields:
      - name: name
        type: string
        required: true

  - name: Articles
    path: _data/ArticlesData
    type: collection
    format: json
    filename: "{primary}.json"
    
    view:
      fields: [Title, Topic, Published, ReleaseDate, LastUpdated]
      primary: Title
      sort: [ReleaseDate, Title]
      default:
          sort: ReleaseDate
          order: desc
        
    fields:
      - name: Title
        type: string
        required: true
        
      - name: Topic
        type: reference # Changed from select to reference
        required: true
        options:
          collection: ArticleCategories # Points directly to your collection
          field: name # The field inside the category file to display/save
          placeholder: Select the category of the Article
          label: "{primary}"
        
      - name: Published
        type: boolean
        default: false

      - name: Comments
        type: boolean
        default: true
        
      - name: Likes
        type: boolean
        default: true

      - name: ReadTime
        type: number
        options:
          min: 1
        
      - name: Description
        type: rich-text
        options:
          switcher: false
        
      - name: Body
        type: rich-text
        required: true
        options:
          switcher: false
        
      - name: ReleaseDate
        type: date
        required: true
        
      - name: LastUpdated
        type: date
        
  