media: files
content:
  - name: Articals
    label: Articals
    path: Data
    type: collection
    
    view:
      fields: [Title, Category, Published, ReleaseDate, LastUpdated]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
        
    fields:
      - name: Title
        type: string
        required: true
        
      - name: Category
        type: select
        required: true
        options:
          values: [Science, Space, Politics, Sports]
        
      - name: Published
        type: boolean
        default: false

      - name: Comments
        type: boolean
        default: true
        
      - name: Likes
        type: boolean
        default: true
        
      - name: Description
        type: text
        
      - name: Body
        type: rich-text
        required: true
        
      - name: ReleaseDate
        type: date
        required: true
        
      - name: LastUpdated
        type: date
        
        
  