media: files

content:
  - name: AboutAuthor
    type: file
    path: Data/AboutAuthor
    fields:
      - name: AuthorName
        type: string

      - name: AuthorImage
        type: image
        
      - name: Desciption
        type: rich-text
        options:
          switcher: false

        
  - name: Articals
    path: Data/Articals
    type: collection
    
    view:
      fields: [Title, Category, Published, ReleaseDate, LastUpdated]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
        
    fields:
      - name: Title
        type: string
        required: true
        
      - name: Category
        type: select
        required: true
        options:
          values: [Science, Space, Politics, Sports]
          placeholder: Select the category of the Artical
        
      - name: Published
        type: boolean
        default: false

      - name: Comments
        type: boolean
        default: true
        
      - name: Likes
        type: boolean
        default: true
        
      - name: Description
        type: rich-text
        options:
          switcher: false
        
      - name: Body
        type: rich-text
        required: true
        options:
          switcher: false
        
      - name: ReleaseDate
        type: date
        required: true
        
      - name: LastUpdated
        type: date
        
  